image: docker:20.10.21

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

scan-code:
  stage: .pre
  image:
    name: "zricethezav/gitleaks:v8.15.2"
    entrypoint: [""]
  script:
    - gitleaks detect --verbose --redact --no-git --source="$CI_PROJECT_DIR"
  tags:
    - docker

scan-vulnerabilities:
  stage: .pre
  image:
    name: "aquasec/trivy:0.35.0"
    entrypoint: [""]
  script:
    - trivy fs --no-progress --ignore-unfixed --exit-code 0 $CI_PROJECT_DIR
  allow_failure: true
  tags:
    - docker

test-code:
  image: azul/zulu-openjdk:19
  stage: test
  script:
    - chmod +x gradlew
    - ./gradlew jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html
  coverage: "/Total.*?([0-9]{1,3})%/"
  tags:
    - gitlab-org-docker
