## Specific image for DinD
image: docker:19.03.15

# DinD (Docker in Docker) service is required for test containers
services:
  - docker:dind

## Environment variables
variables:
  # Instruct test containers to use the daemon of DinD
  DOCKER_HOST: "tcp://docker:2375"

  # Specify to Docker where to create the certificates, Docker will
  # create them automatically on boot, and will create
  # `/certs/client` that will be shared between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: ""

  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

## Job test_code
## - run unit tests
## - evaluate test coverage 
test_code:
  image: openjdk:17
  stage: test
  script:
    - sh ./gradlew -S test jacocoTestReport sonarqube
    - cat build/reports/jacoco/test/html/index.html
  tags:
    - DOCKER
