image: docker:19.03.15

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

test_code:
  image: openjdk:17
  stage: test
  script:
    - sh ./gradlew -S test jacocoTestReport sonarqube
    - cat build/reports/jacoco/test/html/index.html
  tags:
    - DOCKER

qodana:
  image:
    name: jetbrains/qodana-jvm-community
    entrypoint: [ '' ]
  stage: test
  script:
    - /opt/idea/bin/entrypoint --results-dir=$CI_PROJECT_DIR/qodana --save-report --report-dir=$CI_PROJECT_DIR/qodana/report --baseline=qodana.sarif.json
  artifacts:
    paths:
      - qodana
  tags:
    - docker
