version: '3.5'

services:
  ronja_db:
    image: mysql:5.7.29
    container_name: ronja_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ronja
      MYSQL_PASSWORD: ronja
      MYSQL_DATABASE: ronja
    volumes:
      - dbronja:/var/lib/mysql/

volumes:
  dbronja:
    driver: local
