name: Application Deploy

on:
  workflow_run:
    workflows: [ Application Tests ]
    types: [ completed ]
    branches: [ master ]

jobs:
  changes:
    name: Detect relevant source changes
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      main: ${{ steps.filter.outputs.main }}
      gradle: ${{ steps.filter.outputs.gradle }}
      dockerfile: ${{ steps.filter.outputs.dockerfile }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Run changes detection
        uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: |
            main:
              - 'src/main/**'
            gradle:
              - 'build.gradle'
            dockerfile:
              - 'Dockerfile'

  build-docker-image:
    name: Build and deploy the docker image
    needs: changes
    runs-on: ubuntu-22.04
    if: ${{ needs.changes.outputs.main == 'true' || needs.changes.outputs.gradle == 'true' || needs.changes.outputs.dockerfile == 'true' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64, amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: beo1975/ronja-server:1.3.3
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.4
        with:
          app_name: beo-1975-ronja-server
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
                  {
                    "name": "beo-1975-ronja-server",
                    "image":{
                      "registry_type": "DOCKER_HUB",
                      "registry": "beo1975",
                      "repository": "ronja-server",
                      "tag": "1.3.3"
                    }
                  }
                ]'