name: Build and Test

on:
  push:
  pull_request:

jobs:
  build-and-test:

    runs-on: ubuntu-20.04
    name: Build and Test the Application
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Setup Cache      
      uses: actions/cache@v3
      with:
        fetch-depth: 0
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-jdk18-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-jdk18-      

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        java-package: jdk

    - name: Run Tests and Code Analysis
      run: ./gradlew test

    - name: Run Code Analysis
      run: ./gradlew sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64, amd64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2


    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build Docker image and push to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64, linux/arm64
        push: true
        tags: beo1975/ronja-server:1.3.2
