name: Build and Test the Project with Gradle

on:
  push:
  pull_request:

jobs:
  build-and-test:

    runs-on: ubuntu-20.04
    name: Build and Test the Application
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup Cache      
      uses: actions/cache@v2
      with:
        fetch-depth: 0
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-jdk17-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-jdk17-      

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        java-package: jdk

    - name: Run Tests and Code Analysis
      run: ./gradlew test

    - name: Run Code Analysis
      run: ./gradlew sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
